### ISSUE TITLE
GSOC svgene project undertaking

### ISSUE THREAD

**Issue by ianubhav** [kblin/svgene#1]
Hi @kblin ,
I was interested in undertaking this as my gsoc project and I have nice experience with D3 js. Need some assistance from you.

**Comment by kblin** [comment]
Hey @ianubhav,
Happy to help out, do you have any specific questions?

**Comment by ianubhav** [comment]
Hi @kblin ,
A few questions.

1) Is antismash required to be installed or all the work can be done by svgene itself?
2) You've mentioned that zooming and panning is needed. I got some idea but wanted a clear picture of it
2) I also wanted to confirm if only the work on svgene is to be done to get the GSOC project accepted?
3) What other factors are required to get the project accepted?

**Comment by ianubhav** [comment]
Hi @kblin ,
Gentle Remainder

**Comment by kblin** [comment]
I'm afraid I have quite a number of things I'm working on, and non-trivial questions can sometimes take me a bit longer to reply to.

I don't think an antiSMASH install is needed to do this project, but of course it is helpful to keep in mind how this project will be used.

Zooming and panning is the main focus, but additional details should be displayed at a close enough zoom level. Some thought needs to go into how that data can be loaded on demand. I think an AJAX option would be great, but one of the use cases of SVGene is a static web page that needs to be able to load offline, from a local disk.

The remaining two questions are a bit tricky to answer in a general fashion. This is only a project idea, and of course we do expect students to flesh out the ideas a bit. I'm happy to answer further questions you might have to do this.

**Comment by ianubhav** [comment]
Hi @kblin ,
Is there anyplace or a link where I could see some usage of svgene with the antismash library. The antismash library felt a bit complicated to me.

**Comment by kblin** [comment]
There's multiple uses of svgene in the example output: http://antismash.secondarymetabolites.org/upload/example/index.html
Also, see https://github.com/antismash/antismash/blob/master/antismash/output_modules/html/js.py for the logic generating the json file that is loaded by the main html file.

**Comment by ianubhav** [comment]
Hi @kblin ,
I just submitted a proposal. I know that you are a very busy person, but if you have time please review and let me know if something extra could be added.

**Comment by kblin** [comment]
I can't access the proposal file, I'm afraid. Can you give access to kblin@biosustain.dtu.dk

**Comment by ianubhav** [comment]
Hi @kblin ,
Updated the docs. Please review it when you have some time.

Thankyou

**Comment by ianubhav** [comment]
Hi @kblin ,
I just wanted to know my chances of getting the proposal accepted. If you think there is a high chance to that, then I could start doing some work from now itself.

**Comment by kblin** [comment]
I'm afraid we're not allowed to discuss this with students prior to Google's announcement.
